#ifndef TYPE_DEFINITIONS_H
#define TYPE_DEFINITIONS_H

#define FOREACH_TYPE(TYPE) \
  TYPE(PLAYER) \
  TYPE(ENEMY) \
  TYPE(ELEMENT) \
  TYPE(TENSOR) \
  TYPE(MATRIX) \
  TYPE(VECTOR) \
  TYPE(BUTTON) \
  TYPE(TEXT) \

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

typedef enum {
  FOREACH_TYPE(GENERATE_ENUM)
  TYPE_COUNT
} TYPE;

extern char *TYPE_STRING[];

#endif
